import com.jwebmp.core.databind.IOnComponentAdded;
import com.jwebmp.plugins.bootstrap.implementations.BootstrapModuleInclusion;
import com.jwebmp.plugins.bootstrap.implementations.OnBootstrapComponentAdded;

module com.jwebmp.plugins.bootstrap {


    requires transitive com.jwebmp.core.base.angular.client;
    requires com.jwebmp.client;
    requires com.jwebmp.core;
    requires com.jwebmp.core.angular;
    requires com.jwebmp.angular.forms;

    requires com.google.common;

    requires static lombok;

    requires com.guicedee.guicedinjection;
    requires com.guicedee.jsonrepresentation;

    exports com.jwebmp.plugins.bootstrap;
    exports com.jwebmp.plugins.bootstrap.accordion;
    exports com.jwebmp.plugins.bootstrap.alerts.events;
    exports com.jwebmp.plugins.bootstrap.alerts.styles;
    exports com.jwebmp.plugins.bootstrap.alerts;
    exports com.jwebmp.plugins.bootstrap.badge;
    exports com.jwebmp.plugins.bootstrap.badge.styles;
    exports com.jwebmp.plugins.bootstrap.breadcrumbs;
    exports com.jwebmp.plugins.bootstrap.buttons;
    exports com.jwebmp.plugins.bootstrap.buttons.checkbox.styles;
    exports com.jwebmp.plugins.bootstrap.buttons.checkbox;
    exports com.jwebmp.plugins.bootstrap.buttons.groups;
    exports com.jwebmp.plugins.bootstrap.buttons.groups.interfaces;
    exports com.jwebmp.plugins.bootstrap.buttons.groups.options;
    exports com.jwebmp.plugins.bootstrap.buttons.radio.styles;
    exports com.jwebmp.plugins.bootstrap.buttons.radio;
    exports com.jwebmp.plugins.bootstrap.buttons.switches;
    exports com.jwebmp.plugins.bootstrap.buttons.styles;
    exports com.jwebmp.plugins.bootstrap.buttons.toolbars;
    exports com.jwebmp.plugins.bootstrap.cards;
    exports com.jwebmp.plugins.bootstrap.cards.layout;
    exports com.jwebmp.plugins.bootstrap.cards.parts;
    exports com.jwebmp.plugins.bootstrap.cards.parts.interfaces;
    exports com.jwebmp.plugins.bootstrap.cards.parts.styles;
    exports com.jwebmp.plugins.bootstrap.cards.prebuilt;
    exports com.jwebmp.plugins.bootstrap.cards.themed;
    exports com.jwebmp.plugins.bootstrap.carousel;
    exports com.jwebmp.plugins.bootstrap.carousel.parts;
    exports com.jwebmp.plugins.bootstrap.carousel.events;
    exports com.jwebmp.plugins.bootstrap.carousel.features;
    exports com.jwebmp.plugins.bootstrap.carousel.options;
    exports com.jwebmp.plugins.bootstrap.close;
    exports com.jwebmp.plugins.bootstrap.collapse;
    exports com.jwebmp.plugins.bootstrap.collapse.features;
    exports com.jwebmp.plugins.bootstrap.containers;
    exports com.jwebmp.plugins.bootstrap.datepicker;
    //exports com.jwebmp.plugins.bootstrap.datetimepicker;
    exports com.jwebmp.plugins.bootstrap.dropdown;
    exports com.jwebmp.plugins.bootstrap.dropdown.parts;
    exports com.jwebmp.plugins.bootstrap.dropdown.interfaces;
    exports com.jwebmp.plugins.bootstrap.dropdown.options;
    //exports com.jwebmp.plugins.bootstrap4.enumerations;
    exports com.jwebmp.plugins.bootstrap.figures;
    exports com.jwebmp.plugins.bootstrap.forms;
    exports com.jwebmp.plugins.bootstrap.forms.groups;
    exports com.jwebmp.plugins.bootstrap.forms.groups.enumerations;
    exports com.jwebmp.plugins.bootstrap.forms.groups.sets;
    exports com.jwebmp.plugins.bootstrap.forms.groups.sets.parts;
    exports com.jwebmp.plugins.bootstrap.forms.controls;
    exports com.jwebmp.plugins.bootstrap.forms.interfaces;
    exports com.jwebmp.plugins.bootstrap.images;
    exports com.jwebmp.plugins.bootstrap.jumbotron;
    exports com.jwebmp.plugins.bootstrap.jumbotron.interfaces;
    exports com.jwebmp.plugins.bootstrap.listgroup;
    exports com.jwebmp.plugins.bootstrap.listgroup.parts;

    exports com.jwebmp.plugins.bootstrap.media;
    exports com.jwebmp.plugins.bootstrap.media.parts;
    exports com.jwebmp.plugins.bootstrap.modal;
    exports com.jwebmp.plugins.bootstrap.modal.events.hidden;
    exports com.jwebmp.plugins.bootstrap.modal.events.hide;
    exports com.jwebmp.plugins.bootstrap.modal.events.show;
    exports com.jwebmp.plugins.bootstrap.modal.events.shown;
    exports com.jwebmp.plugins.bootstrap.modal.parts;

    exports com.jwebmp.plugins.bootstrap.navbar;
    exports com.jwebmp.plugins.bootstrap.navbar.parts;
    exports com.jwebmp.plugins.bootstrap.navbar.enumerations;
    exports com.jwebmp.plugins.bootstrap.navbar.interfaces;
    exports com.jwebmp.plugins.bootstrap.navbar.toggler;
    exports com.jwebmp.plugins.bootstrap.navs;
    exports com.jwebmp.plugins.bootstrap.navs.parts;
    exports com.jwebmp.plugins.bootstrap.navs.interfaces;
    exports com.jwebmp.plugins.bootstrap.options;
    exports com.jwebmp.plugins.bootstrap.options.interfaces;
    exports com.jwebmp.plugins.bootstrap.pagination;
    exports com.jwebmp.plugins.bootstrap.pagination.parts;
    exports com.jwebmp.plugins.bootstrap.pagination.options;
    exports com.jwebmp.plugins.bootstrap.popovers;
    exports com.jwebmp.plugins.bootstrap.popovers.interfaces;
    exports com.jwebmp.plugins.bootstrap.progressbar;
//	exports com.jwebmp.plugins.bootstrap.progressbar.bar;
    exports com.jwebmp.plugins.bootstrap.progressbar.interfaces;
    exports com.jwebmp.plugins.bootstrap.select;
    exports com.jwebmp.plugins.bootstrap.range;
    exports com.jwebmp.plugins.bootstrap.tables;
    exports com.jwebmp.plugins.bootstrap.toggle;
    exports com.jwebmp.plugins.bootstrap.toasts;
    exports com.jwebmp.plugins.bootstrap.toasts.features;
    exports com.jwebmp.plugins.bootstrap.toasts.events;
    exports com.jwebmp.plugins.bootstrap.timepicker;
//	exports com.jwebmp.plugins.bootstrap.tooltips;

    provides com.jwebmp.core.services.IPageConfigurator with com.jwebmp.plugins.bootstrap.BootstrapPageConfigurator;
    provides com.guicedee.client.services.config.IGuiceScanModuleInclusions with BootstrapModuleInclusion;
    provides IOnComponentAdded with OnBootstrapComponentAdded;


    opens com.jwebmp.plugins.bootstrap to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.accordion to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.alerts.events to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.alerts.styles to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.alerts to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.badge to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.badge.styles to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.breadcrumbs to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.buttons to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.buttons.checkbox.styles to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.buttons.checkbox to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.buttons.groups to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.buttons.groups.interfaces to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.buttons.groups.options to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.buttons.radio.styles to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.buttons.radio to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.buttons.styles to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.buttons.toolbars to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.cards to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.cards.layout to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.cards.parts to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.cards.parts.interfaces to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.cards.parts.styles to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.cards.prebuilt to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.cards.themed to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.carousel to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.carousel.parts to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.carousel.events to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.carousel.features to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.carousel.options to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.close to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.collapse to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.collapse.events.hidden to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.collapse.events.hide to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.collapse.events.show to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.collapse.events.shown to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.collapse.features to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.containers to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.datepicker to tools.jackson.databind, com.jwebmp.core;
    //  opens com.jwebmp.plugins.bootstrap.datetimepicker to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.dropdown to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.dropdown.parts to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.dropdown.events.hidden to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.dropdown.events.hide to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.dropdown.events.show to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.dropdown.events.shown to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.dropdown.interfaces to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.dropdown.options to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.figures to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.forms to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.forms.groups to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.forms.groups.enumerations to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.forms.groups.sets to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.forms.groups.sets.parts to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.forms.controls to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.forms.interfaces to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.images to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.implementations to com.google.guice, tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.jumbotron to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.jumbotron.interfaces to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.listgroup to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.listgroup.parts to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.navbar.toggler to tools.jackson.databind, com.jwebmp.core;

    opens com.jwebmp.plugins.bootstrap.media to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.media.parts to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.modal to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.modal.events.hidden to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.modal.events.hide to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.modal.events.show to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.modal.events.shown to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.modal.parts to tools.jackson.databind, com.jwebmp.core;
//	opens com.jwebmp.plugins.bootstrap.modal.features to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.navbar to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.navbar.parts to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.navbar.enumerations to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.navbar.interfaces to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.navs to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.navs.parts to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.navs.interfaces to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.options to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.select to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.options.interfaces to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.pagination to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.pagination.parts to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.pagination.options to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.popovers to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.popovers.interfaces to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.progressbar to tools.jackson.databind, com.jwebmp.core;
//	opens com.jwebmp.plugins.bootstrap.progressbar.bar to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.progressbar.interfaces to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.range to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.tables to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.toasts to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.toasts.features to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.toasts.events to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.toggle to tools.jackson.databind, com.jwebmp.core;
    opens com.jwebmp.plugins.bootstrap.timepicker to tools.jackson.databind, com.jwebmp.core;
//	opens com.jwebmp.plugins.bootstrap.tooltips to tools.jackson.databind, com.jwebmp.core;

    provides com.jwebmp.core.databind.IOnComponentConfigured with com.jwebmp.plugins.bootstrap.implementations.OnBootstrapComponentAdded;
}
